### ISSUE TITLE
problem with load keyword for SortedSet...

### ISSUE THREAD

**Issue by TermeHansen** [mcocdawc/chemcoord#54]
#### Code Sample, a copy-pastable example if possible

`cc.Cartesian.read_xyz('temp.xyz')
`
#### Problem description

problem with reading in Cartesian coordinates, as for some reason with pip install of chemcoord and dependency sortedcontainers it fails with:
```
"/usr/local/lib/python3.6/dist-packages/chemcoord/cartesian_coordinates/_cartesian_class_core.py", line 486, in <dictcomp>
    for key in bond_dict}
TypeError: __init__() got an unexpected keyword argument 'load'

```

removing "load=20" from 
https://github.com/mcocdawc/chemcoord/blob/cc4aa1de8c77c71e66c9c1807e350f3a812bac8f/src/chemcoord/cartesian_coordinates/_cartesian_class_core.py#L485

seems to solve the issue...

#### Output of ``cc.show_versions()``

<details>
INSTALLED VERSIONS
------------------
python: 3.6.3.final.0
python-bits: 64
OS: Linux
OS-release: 4.12.14-1-MANJARO
machine: x86_64
processor: 
LC_ALL: None
LANG: en_DK.UTF-8
LOCALE: en_DK.UTF-8

chemcoord: 2.0.3
numpy: 1.13.3
scipy: 0.19.1
pandas: 0.20.3
numba: 0.36.2
sortedcontainers: 1.5.9
sympy: 1.1.1
pytest: 3.3.1
pip: 9.0.1
setuptools: 38.2.4
IPython: 6.2.1
sphinx: None

</details>

**Comment by smheidrich** [comment]
I stumbled across this as well (``Cartesian.get_zmat`` fails for the same reason). Seems like the ``load`` parameter got removed in *sortedcontainers* 1.5.9: https://github.com/grantjenks/sorted_containers/commit/c53d6c4f736c08646c4588800b8bcbb78a9bc68d
It works fine with the previous release (1.5.7).

**Comment by mcocdawc** [comment]
Sorry for my late answer :/ and thank you very much for solving and spotting.
If you want to make a pull request with your changes I will happily accept it.
Otherwise I would just copy-paste your solution.

**Comment by TermeHansen** [comment]
I am just using chemcoord from pypi, and not from git so it is fine for me if you just remove the ", load=29" part yourself.

How long is the iteration on getting new commits in a new release on pypi usually?

**Comment by mcocdawc** [comment]
Hard to say but if I it's such a bug that basically prevents using the library, I will upload a new wheel in the next days.

**Comment by mcocdawc** [comment]
And @smheidrich thanks for your observation. It's good to know, that it wasn't wrong in the beginning. ;)

**Comment by mcocdawc** [comment]
new version is now uploaded to pipy.
